// <auto-generated />
using System;
using HamsterKindergarden_Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HamsterKindergarden_Db.Migrations
{
    [DbContext(typeof(HamsterContext))]
    [Migration("20210407091202_InitiateCreate")]
    partial class InitiateCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HamsterKindergarden_Simulation.ActivitieCage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tickcounter")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("activitieCages");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.Hamster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivitieCageid")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AktivitesCounter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedIn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Countminutes")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("HamsterCageId")
                        .HasColumnType("int");

                    b.Property<string>("LatestActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ActivitieCageid");

                    b.HasIndex("HamsterCageId");

                    b.ToTable("hamster");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.HamsterCage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HamsterCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("hamstercage");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("ActivityDuration")
                        .HasColumnType("time");

                    b.Property<DateTime>("ActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HamsterActivity")
                        .HasColumnType("int");

                    b.Property<int?>("HamsterID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HamsterID");

                    b.ToTable("AktivityLog");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.Hamster", b =>
                {
                    b.HasOne("HamsterKindergarden_Simulation.ActivitieCage", null)
                        .WithMany("activities")
                        .HasForeignKey("ActivitieCageid");

                    b.HasOne("HamsterKindergarden_Simulation.HamsterCage", null)
                        .WithMany("Hamsters")
                        .HasForeignKey("HamsterCageId");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.Log", b =>
                {
                    b.HasOne("HamsterKindergarden_Simulation.Hamster", null)
                        .WithMany("ActivityList")
                        .HasForeignKey("HamsterID");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.ActivitieCage", b =>
                {
                    b.Navigation("activities");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.Hamster", b =>
                {
                    b.Navigation("ActivityList");
                });

            modelBuilder.Entity("HamsterKindergarden_Simulation.HamsterCage", b =>
                {
                    b.Navigation("Hamsters");
                });
#pragma warning restore 612, 618
        }
    }
}
